# Train-Test Split

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split 

# Generate some data

In [5]:
a = np.arange(1,101)
b = np.arange(101,201)

# Split the data

In [7]:
a_train, a_test = train_test_split(a)

In [8]:
a_train

array([ 64,   3,  12,  61,  57,  93,  17,  33,  68,   8,  50,   2,  75,
        94,  49,  41,  58,  37,  77,  78,  69,  70,  76,  47,  54,  80,
        10,   1,  96,  62,  60,  32,  34,  39,  92,  25,  52,  89,  15,
        56,  35,  85,  21,  66,  30, 100,   5,  73,  27,  83,  16,  67,
         7,  86,  97,  29,  87,  74,  65,  42,  90,  51,  38,  79,  31,
        84,  72,  53,  95,  40,  26,  81,  55,   6,  98])

In [ ]:
a_test

# Checking the percentages for the split

In [11]:
a_train.shape, a_test.shape

((75,), (25,))

# Changing the ratio of split

In [13]:
a_train, a_test = train_test_split(a, test_size =0.2)

In [15]:
a_train.shape, a_test.shape

((80,), (20,))

# To turn off the shuffle

In [16]:
b_train, b_test = train_test_split(b, test_size =0.2, shuffle = False)

In [17]:
b_train

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180])

In [18]:
b_test

array([181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,
       194, 195, 196, 197, 198, 199, 200])

# To get the same shuffle every time you run a code

In [22]:
a_train, a_test = train_test_split(a, test_size =0.2, random_state = 42)

In [24]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [25]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [19]:
b_train, b_test = train_test_split(b, test_size =0.2, random_state = 42)

In [20]:
b_train

array([156, 189, 127, 143, 170, 116, 141, 197, 110, 173, 112, 148, 186,
       129, 194, 106, 167, 166, 136, 117, 150, 135, 108, 196, 128, 120,
       182, 126, 163, 114, 125, 104, 118, 139, 109, 179, 107, 165, 137,
       190, 157, 200, 155, 144, 151, 168, 147, 169, 162, 198, 180, 142,
       159, 149, 199, 158, 176, 133, 195, 160, 164, 185, 138, 130, 102,
       153, 122, 103, 124, 188, 192, 175, 187, 183, 121, 161, 172, 115,
       193, 152])

In [21]:
b_test

array([184, 154, 171, 146, 145, 140, 123, 181, 111, 101, 119, 131, 174,
       134, 191, 105, 177, 178, 113, 132])